.\" (C) Copyright 2018 Pavel Rehak <pavel-rehak@email.cz>,
.\"
.TH MKVTOMP4 1 "April 17 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
mkvtomp4 \- GUI tool for converting mkv files to mp4
.SH SYNOPSIS
.B mkvtomp4
.RI [ option ]
.SH DESCRIPTION
.B mkvtomp4
can:
  * Repack mkv to mp4 file,
  * video si copied without converting,
  * aac audio si copied without converting,
  * other audio formats (mp3, ac3) are converted to aac,
  * optionally, it is possible to add artwork.
.PP
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show the mkvtomp4 version.
